<?php /** @var $this \Dlayer\ViewHelper\ViewHelperCodeCompletion */ ?>

<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Dlayer: Content manager preview');

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
            ->prependStylesheet($this->basePath('node_modules/bootstrap/dist/css/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/site.css'))
            ->prependStylesheet($this->basePath('node_modules/font-awesome/css/font-awesome.min.css'));

        echo $this->headScript()
            ->prependFile($this->basePath('node_modules/bootstrap/dist/js/bootstrap.js'))
            ->prependFile($this->basePath('node_modules/popper.js/dist/umd/popper.js'))
            ->prependFile($this->basePath('node_modules/jquery/dist/jquery.js'));
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            <a class="navbar-brand" href="/"><img src="<?php echo $this->basePath('images/brand.jpg'); ?>" width="30" height="30" alt=""></a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTop">
                <ul class="navbar-nav mr-auto">
                    <?php foreach($this->layout()->navbar as $item) { ?>
                        <li class="nav-item<?php if(array_key_exists('active', $item) === true && $item['active'] === true) { echo ' active'; } ?>">
                        <a class="nav-link" href="<?php echo $this->escapeHtmlAttr($item['uri']); ?>"><?php echo $this->escapeHtml($item['name']); ?></a>
                    </li>
                    <?php } ?>
                </ul>
                <span class="navbar-text">
                    <a href=""><i class="fa fa-lg fa-sign-out" aria-hidden="true"></i> Sign out</a> - <small>vNext (Day Ordinal Month Year)</small>
                </span>
            </div>
        </nav>
        <div class="container-fluid">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->toolbar()
            ->buttonGroups($this->layout()->toolbar)
            ->buttonGroupsClasses([ 'btn-group-sm', 'ml-3' ])
            ->buttonGroupLeft($this->layout()->toolbar_left)
            ->buttonGroupRight($this->layout()->toolbar_right)
            ->buttonGroupClassesLeft([ 'btn-group-sm' ])
            ->buttonGroupClassesRight([ 'btn-group-sm', 'ml-auto' ]); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
