<?php /** @var $this \Dlayer\ViewHelper\ViewHelperCodeCompletion */ ?>

<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('Dlayer: Content manager preview');

        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
            ->prependStylesheet($this->basePath('node_modules/bootstrap/dist/css/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/site.css'))
            ->prependStylesheet($this->basePath('node_modules/font-awesome/css/font-awesome.min.css'));

        echo $this->headScript()
            ->prependFile($this->basePath('node_modules/bootstrap/dist/js/bootstrap.js'))
            ->prependFile($this->basePath('node_modules/popper.js/dist/umd/popper.js'))
            ->prependFile($this->basePath('node_modules/jquery/dist/jquery.js'));
        ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            <a class="navbar-brand" href="/"><img src="<?php echo $this->basePath('images/brand.jpg'); ?>" width="30" height="30" alt=""></a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarTop" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTop">
                <ul class="navbar-nav mr-auto">
                    <?php foreach($this->layout()->navbar as $item) { ?>
                        <li class="nav-item<?php if(array_key_exists('active', $item) === true && $item['active'] === true) { echo ' active'; } ?>">
                        <a class="nav-link" href="<?php echo $this->escapeHtmlAttr($item['uri']); ?>"><?php echo $this->escapeHtml($item['name']); ?></a>
                    </li>
                    <?php } ?>
                </ul>
                <span class="navbar-text">
                    <a href=""><i class="fa fa-lg fa-sign-out" aria-hidden="true"></i> Sign out</a> - <small>vNext (Day Ordinal Month Year)</small>
                </span>
            </div>
        </nav>
        <div class="container-fluid mb-3">
            <div class="row content-manager">
                <div class="col-xl-9 col-lg-9 col-md-12">
                    <?php echo $this->content; ?>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-12 tool-form">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" style="padding: 0.3rem 0.8rem;" id="tab1-tab" data-toggle="tab" href="#tab1" role="tab" aria-controls="tab1" aria-expanded="true"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab2-tab" data-toggle="tab" href="#tab2" role="tab" aria-controls="tab2"><i class="fa fa-tint" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab3-tab" data-toggle="tab" href="#tab3" role="tab" aria-controls="tab3"><i class="fa fa-font" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab4-tab" data-toggle="tab" href="#tab4" role="tab" aria-controls="tab4"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab5-tab" data-toggle="tab" href="#tab5" role="tab" aria-controls="tab5"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                    <div class="tab-content p-3" id="myTabContent" style="border-left: 1px solid #dddddd;">
                        <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
                            <h4>Jumbotron</h4>

                            <p class="lead">Tool form here...</p>
                        </div>
                        <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
                            <h4>Styling</h4>

                            <p class="lead">Tool form here...</p>
                        </div>
                        <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="tab3-tab">
                            <h4>Typography</h4>

                            <p class="lead">Tool form here...</p>

                            <p>Tool help full text</p>
                        </div>
                        <div class="tab-pane fade" id="tab4" role="tabpanel" aria-labelledby="tab4-tab">
                            <h4>Delete</h4>

                            <p class="lead">Tool form here...</p>

                            <p>Tool help full text</p>
                        </div>
                        <div class="tab-pane fade" id="tab5" role="tabpanel" aria-labelledby="tab5-tab">
                            <h4>Typography</h4>

                            <p class="lead">Tool help intro...</p>

                            <p>Tool help full text</p>

                            <p><a class="btn btn-outline-primary btn-sm" href="#">Link to online docs</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->toolbar('dlayer_toolbar')
            ->addTools($this->layout()->toolbar['middle'])
            ->setClassForToolGroups([ 'btn-group', 'btn-group-sm', 'ml-3' ])
            ->addToolsToLeft($this->layout()->toolbar['left'])
            ->addToolsToRight($this->layout()->toolbar['right'])
            ->setClassesForLeftToolGroup([ 'btn-group', 'btn-group-sm' ])
            ->setClassesForRightToolGroup([ 'btn-group', 'btn-group-sm', 'ml-auto' ])
            ->setActiveTool($this->layout()->toolbar['active'])
            ->fixedBottom(); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
