<div class="row">
    <div class="col-xl-12">
        <h2>Content manager development</h2>

        <ul>
            <li><a href="/content/manager">Dev</a> - Sample HTML</li>
            <li><a href="/content/manager/row-selected">Row selected</a> - A row has been selected</li>
            <li><a href="/content/manager/column-selected">Column selected</a> - A column has been selected</li>
            <li><a href="/content/manager/tool-selected">Tool selected</a> - Add a content item/row to a column</li>
            <li><a href="/content/manager/tool-and-item-selected">Tool and item selected</a> - Edit the selected content item</li>
        </ul>
    </div>
</div>
