<div class="row">
    <div class="col-xl-12">
        <h2>Content manager development</h2>

        <ul>
            <li><a href="/content/manager">General overview</a></li>
            <li><a href="/content/manager/tool-and-item-selected">Tool and item selected</a> - Edit mode</li>
            <li><a href="/content/manager/tool-selected">Tool selected</a> - Add mode</li>
        </ul>
    </div>
</div>
