<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-lg-12">
        <h2>Badge</h2>

        <p>Go back to the helpers <a href="/helpers">root</a>.</p>

        <pre>
            $this->bootstrap4Badge('Badge')->setStyle('primary')->pill();
        </pre>

        <?php
        echo $this->bootstrap4Badge('Badge')->setStyle('primary')->pill();
        ?>
    </div>
</div>
