<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-xl-12">
        <h2>Button</h2>

        <p>Go back to the helpers <a href="/helpers">root</a>.</p>

        <pre>
            $this->bootstrap4Button('Button')->
            setStyle('info')->
            setModeInput('submit')->
            disabled();
        </pre>

        <?php
        echo $this->bootstrap4Button('Button')->
            setStyle('info')->
            setModeInput('submit')->
            disabled();
        ?>
    </div>
</div>
