<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-xl-12">
        <h2>Jumbotron</h2>

        <p>Go back to the helpers <a href="/helpers">root</a>.</p>

        <pre>
            $this->bootstrap4Jumbotron(
                'Heading',
                '<p class="lead">This is an example of a jumbotron</p>')
            ->setHeadingDisplayLevel(1)
            ->setBgStyle('light');
        </pre>

        <?php
        echo $this->bootstrap4Jumbotron(
                'Heading',
                '<p class="lead">This is an example of a jumbotron</p>')
            ->setHeadingDisplayLevel(1)
            ->setBgStyle('light');
        ?>
    </div>
</div>
