<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-lg-12">
        <h2>Navbar</h2>

        <p>Go back to the helpers <a href="/helpers">root</a>.</p>

        <pre>
            $this->bootstrap4NavbarLite()->
            addBrand('Dlayer', '/')->
            addNavigation([ ['uri' => 'http://www.google.com', 'label' => 'Item 1', 'active' => false ] ]);
        </pre>

        <?php
        echo $this->bootstrap4NavbarLite()->
            addBrand('Dlayer', '/')->
            addNavigation([ ['uri' => 'http://www.google.com', 'label' => 'Item 1', 'active' => false ] ]);
        ?>
    </div>
</div>
