<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-xl-12">
        <h2>Progress bar</h2>

        <p>Go back to the helpers <a href="/helpers">root</a>.</p>

        <pre>
            $this->bootstrap4ProgressBar(25)->
            color('danger')->
            height(10)->
            animate()->
            striped();
        </pre>

        <?php
        echo $this->bootstrap4ProgressBar(25)->
            color('danger')->
            height(10)->
            animate()->
            striped();
        ?>
    </div>
</div>
