<div class="row content-manager mb-5">
    <div class="col-xl-9 col-lg-9 col-md-12">
        <div class="container wysiwyg mb-5">
            <div class="row">
                <div class="col-md-12" style="border: 1px solid #93d0e1;">
                    <div class="jumbotron">
                        <h1 class="display-3">Hello, world!</h1>
                        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling
                            extra attention to featured content or information.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p>Morbi ultrices accumsan tortor, quis bibendum metus convallis eu. Phasellus in dictum dui. Cras
                        bibendum viverra vestibulum. Fusce vel accumsan dui, at blandit sem. Aenean rutrum eu sapien
                        vel viverra. Sed accumsan convallis tellus id mollis.</p>

                    <p>Morbi ultrices accumsan tortor, quis bibendum metus convallis eu. Phasellus in dictum dui. Cras
                        bibendum viverra vestibulum. Fusce vel accumsan dui, at blandit sem. Aenean rutrum eu sapien
                        vel viverra. Sed accumsan convallis tellus id mollis.</p>

                    <h4>Form</h4>

                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Row background colour</label>
                            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                            <small id="emailHelp" class="form-text text-muted">Set the background colour for the row.</small>
                        </div>
                        <button type="submit" class="btn btn-success">Save</button>
                    </form>
                </div>
                <div class="col-md-6">
                    <h2>Small heading <small>Smaller heading</small></h2>

                    <img src="<?php echo $this->basePath('images/sample.jpg'); ?>" class="img-fluid" alt="Responsive image">
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-12 tool-form">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" style="padding: 0.3rem 0.8rem;" id="tab1-tab" data-toggle="tab" href="#tab1" role="tab" aria-controls="tab1" aria-expanded="true"><i class="fa fa-bars" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab2-tab" data-toggle="tab" href="#tab2" role="tab" aria-controls="tab2"><i class="fa fa-tint" aria-hidden="true"></i></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" style="padding: 0.3rem 0.8rem;" id="tab3-tab" data-toggle="tab" href="#tab3" role="tab" aria-controls="tab3"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
            </li>
        </ul>
        <div class="tab-content p-3" id="myTabContent" style="border-left: 1px solid #dddddd;">
            <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
                <h4>Column</h4>

                <h6><i class="fa fa-play-circle" aria-hidden="true"></i> Add a new column</h6>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra vitae
                    odio non viverra.</p>

                <p><a class="btn btn-outline-info btn-sm" href="#">Add column(s)</a></p>

                <h6><i class="fa fa-play-circle" aria-hidden="true"></i> Select an existing column</h6>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra vitae
                    odio non viverra.</p>

                <h6><i class="fa fa-play-circle" aria-hidden="true"></i> Edit the selected row</h6>

                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra vitae
                    odio non viverra.</p>

            </div>
            <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
                <h4>Styling</h4>

                <form>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Row background colour</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                        <small id="emailHelp" class="form-text text-muted">Set the background colour for the row.</small>
                    </div>
                    <button type="submit" class="btn btn-outline-success">Save</button>
                </form>
            </div>
            <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="tab3-tab">
                <h4>Help</h4>

                <p class="lead">Tool help intro...</p>

                <p>Tool help full text</p>

                <p><a class="btn btn-outline-primary btn-sm" href="#">Link to online docs</a></p>
            </div>
        </div>
    </div>
</div>
