<?php /** @var $this \Dlayer\ViewHelper\ViewHelperCodeCompletion */ ?>

<div class="container wysiwyg mb-5">
    <div class="row">
        <div class="col-md-12" style="border: 1px solid #93d0e1;">
            <div class="jumbotron">
                <h1 class="display-3">Hello, world!</h1>
                <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling
                    extra attention to featured content or information.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p>Morbi ultrices accumsan tortor, quis bibendum metus convallis eu. Phasellus in dictum dui. Cras
                bibendum viverra vestibulum. Fusce vel accumsan dui, at blandit sem. Aenean rutrum eu sapien
                vel viverra. Sed accumsan convallis tellus id mollis.</p>

            <p>Morbi ultrices accumsan tortor, quis bibendum metus convallis eu. Phasellus in dictum dui. Cras
                bibendum viverra vestibulum. Fusce vel accumsan dui, at blandit sem. Aenean rutrum eu sapien
                vel viverra. Sed accumsan convallis tellus id mollis.</p>

            <h4>Form</h4>

            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Row background colour</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">Set the background colour for the row.</small>
                </div>
                <button type="submit" class="btn btn-success">Save</button>
            </form>
        </div>
        <div class="col-md-6">
            <h2>Small heading <small>Smaller heading</small></h2>

            <img src="<?php echo $this->basePath('images/sample.jpg'); ?>" class="img-fluid" alt="Responsive image">
        </div>
    </div>
</div>
