<div class="row content-manager">
    <div class="col-xl-9 col-lg-9 col-md-12">
        <div class="container wysiwyg">
            <div class="row">
                <div class="col-md-6">
                    <h1>Live view, row 1a</h1>
                </div>
                <div class="col-md-6">
                    <h1>Live view, row 1b</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>Live view, row 2</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>Live view, row 3</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>Live view, row 4</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-12 tool-form">
        <h1>Tools</h1>
    </div>
</div>
