<div class="row">
    <div class="col-lg-12">
        <h2>Zend Framework 3 view helpers</h2>

        <p class="lead">View helper testing/demos</p>

        <ul>
            <li>Badge - Bootstrap 4 badge</li>
            <li>Button - Bootstrap 4 button</li>
            <li>Card - Bootstrap 4 Card</li>
            <li>Jumbotron - Bootstrap 4 Jumbotron</li>
            <li><a href="/helpers/demo/navbar">Navbar (lite)</a> - Bootstrap 4 Navbar</li>
            <li>Progress bar - Bootstrap 4 Progress bar</li>
            <li>Multiple progress bars - Bootstrap 4 Progress bars</li>
        </ul>
    </div>
</div>
