<div class="row">
    <div class="col-xl-12">
        <h2>Zend Framework 3 view helpers</h2>

        <p class="lead">View helper testing/demos</p>

        <ul>
            <li><a href="/helpers/demo/badge">Badge</a> - Bootstrap 4 badge</li>
            <li><a href="/helpers/demo/button">Button</a> - Bootstrap 4 button</li>
            <li><a href="/helpers/demo/card">Card</a> - Bootstrap 4 Card</li>
            <li><a href="/helpers/demo/jumbotron">Jumbotron</a> - Bootstrap 4 Jumbotron</li>
            <li><a href="/helpers/demo/navbar">Navbar (lite)</a> - Bootstrap 4 Navbar</li>
            <li><a href="/helpers/demo/progress-bar">Progress bar</a> - Bootstrap 4 Progress bar</li>
            <li><a href="/helpers/demo/multiple-progress-bars">Multiple progress bars</a> - Bootstrap 4 Progress bars</li>
        </ul>
    </div>
</div>
