<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Dlayer')->setSeparator(' : ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
            ->prependStylesheet($this->basePath('node_modules/bootstrap/dist/css/bootstrap.css'));
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('node_modules/bootstrap/dist/js/bootstrap.js'))
            ->prependFile($this->basePath('node_modules/jquery/dist/jquery.js'));
        ?>
    </head>
    <body>

        <div class="container-fluid">
            <nav class="navbar navbar-toggleable-md navbar-light">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/">Dlayer</a>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Item 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Item 2</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="display-2"><?php echo $this->escapeHtml($this->layout()->title); ?></h1>
                        <p class="lead"><?php echo $this->escapeHtml($this->layout()->tag_line); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <div class="control-bar">
            [Control bar]
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
