<?php /** @var $this \DBlackborough\Zf3ViewHelpersCC\CustomAndZend */?>

<div class="row">
    <div class="col-lg-12">
        <h1>Home</h1>

        <?php echo $this->bootstrap4NavbarLite()->
            addBrand('Dlayer')->
            bgStyle('bg-faded')->
            addNavigation([ ['uri' => 'http://www.google.com', 'label' => 'Item 1', 'active' => false ] ]); ?>

        <?php echo $this->bootstrap4Button('Button')->
            setStyle('info')->
            setModeInput('submit')->
            disabled(); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        ); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        )->fluid(); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        )->headingDisplayLevel(1); ?>

        <?php echo $this->bootstrap4ProgressBar(25)->color('danger')->height(10)->animate()->striped(); ?>

        <?php echo $this->bootstrap4ProgressBarMultiple([25, 25])->color(['danger', 'success'])->height(10)->animate()->striped(); ?>

        <?php echo $this->bootstrap4Card('w-50')->setBody('<p>Card</p>'); ?>
    </div>
</div>
