<?php /** @var $this Application\View\Helper\CodeHinting */?>

<div class="row">
    <div class="col-lg-12">
        <h1>Home</h1>

        <?php echo $this->bootstrap4NavbarLite()->
            addBrand('Dlayer')->
            bgStyle('bg-faded')->
            addNavigation([ ['uri' => 'http://www.google.com', 'label' => 'Item 1', 'active' => false ] ]); ?>

        <?php echo $this->bootstrap4Button('Button')->
            setStyle('info')->
            setModeInput('submit')->
            disabled(); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        ); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        )->fluid(); ?>

        <?php echo $this->bootstrap4Jumbotron(
            'Heading',
            '<p class="lead">This is an example of a jumbotron</p>'
        )->headingDisplayLevel(1); ?>
    </div>
</div>
