<div class="row">
    <div class="col-lg-6">
        <h2>Sign in <small>and start playing with the demo</small></h2>
        <form>
            <div class="form-group">
                <label for="formGroupExampleInput">Username</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="joe@bloggs.com" />
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput2">Password label</label>
                <input type="password" class="form-control" id="formGroupExampleInput2" />
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
        </form>

        <h3 style="margin-top:2rem;">Test credentials</h3>
        <p>Please use one of the below to sign in to the demo.</p>

        <ul>
            <li>
                user-1@dlayer.com / password-1
                <span class="badge badge-success">Account free</span>
            </li>
            <li>
                user-2@dlayer.com / password-2
                <span class="badge badge-success">Account free</span>
            </li>
            <li>
                user-3@dlayer.com / password-3
                <span class="badge badge-success">Account free</span>
            </li>
        </ul>
    </div>
    <div class="col-lg-6">
        <h2>Release history</h2>

        <h3>v1.17 [Name] [Date]</h3>
        <ul>
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
        </ul>

        <h3>v1.16 [Name] [Date]</h3>
        <ul>
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
        </ul>

        <h3>v1.15 [Name] [Date]</h3>
        <ul>
            <li>Item 1</li>
            <li>Item 2</li>
            <li>Item 3</li>
        </ul>

        <hr />

        <h4>And the older releases.</h4>
    </div>
</div>
